[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "zyte-parsers"
description = "Parsing of data from web pages."
authors = [{name = "Zyte Group Ltd", email = "info@zyte.com"}]
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
]
requires-python = ">=3.9"
dependencies = [
    "attrs>=21.3.0",
    "gtin-validator>=1.0.3",
    "html-text",
    "lxml",
    "parsel",
    "price-parser>=0.3.4",
    "python-stdnum>=1.19",
    "six",  # unstated dependency of gtin-validator
    "w3lib",
]
dynamic = ["version"]

[project.urls]
Source = "https://github.com/zytedata/zyte-parsers"

[tool.hatch.version]
path = "zyte_parsers/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/docs",
    "/tests",
    "/zyte_parsers",
    "/CHANGES.rst",
    "/tox.ini",
]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
implicit_reexport = false

# to be fixed
[[tool.mypy.overrides]]
module = ["html_text", "price_parser"]
implicit_reexport = true

[[tool.mypy.overrides]]
module = [
    "gtin.validator.*",
    "stdnum.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "tests.*",
]
# Allow test functions to be untyped
allow_untyped_defs = true
